## Total Score: 130/140

---

---

FYI - I copied over a starting version from the midterm explanation to use for testing your code.

---

In [1]:
import jupyterimporter
from csvlist import CsvList

f = CsvList('/midterm/preexisting.csv')
print(f.header)      # Returns a list of the column names
print(f.data[0:4])    # Returns the list of lists data

importing Jupyter notebook from csvlist.ipynb
['State', 'Federally/State Administered', 'Enrolled Through January 31, 2014  ', 'Enrolled Through December 31, 2013', 'Enrolled Through November 30, 2013', 'Enrolled Through October 31, 2013', 'Enrolled Through September 30, 2013', 'Enrolled Through August 31, 2013', 'Enrolled Through July 31, 2013', 'Enrolled Through June 30, 2013', 'Enrolled Through May 31, 2013', 'Enrolled Through April 30, 2013', 'Enrolled Through Mar. 31, 2013', 'Enrolled Through Feb. 28, 2013', 'Enrolled Through Jan. 31, 2013', 'Enrolled Through Dec. 31, 2012', 'Enrolled Through Nov. 30, 2012', 'Enrolled Through October 31, 2012', 'Enrolled Through September 30, 2012', 'Enrolled Through August 31, 2012', 'Enrolled Through July 31, 2012', 'Enrolled Through June 30, 2012', 'Enrolled Through May 31, 2012', 'Enrolled Through April 30, 2012', 'Enrolled Through March 31, 2012', 'Enrolled Through February 29, 2012', 'Enrolled Through December 31, 2011', 'Enrolled Through No

---

** 30/30 **

---

---

In [3]:
import jupyterimporter
from pivot import pivot_columns

test = [['Last','First','2015Q1','2015Q2','2015Q3','2015Q4'],
        ['Boal','Paul',10,9,10,8],
        ['Westhus','Eric',9,10,10,9]]

out = pivot_columns(test,list(range(2,6)))
out

[['Last', 'First', 'Column', 'Value'],
 ['Boal', 'Paul', '2015Q1', 10],
 ['Boal', 'Paul', '2015Q2', 9],
 ['Boal', 'Paul', '2015Q3', 10],
 ['Boal', 'Paul', '2015Q4', 8],
 ['Westhus', 'Eric', '2015Q1', 9],
 ['Westhus', 'Eric', '2015Q2', 10],
 ['Westhus', 'Eric', '2015Q3', 10],
 ['Westhus', 'Eric', '2015Q4', 9]]

---

** 30/30 **

---

---


In [5]:
import jupyterimporter
from joiner import join_lists

list1 = [['Last','First','Time','Value'],
         ['Boal','Paul','2015Q1',10],
         ['Boal','Paul','2015Q2',9]]

list2 = [['Time','Census'],
         ['2015q1',932],
         ['2015q2',943]]

join_lists(list1, list2, [2], [0], [0,1,2,3], [1])


importing Jupyter notebook from joiner.ipynb
['Census']
[932]
[943]


[['Last', 'First', 'Time', 'Value', 'Census'],
 ['Boal', 'Paul', '2015Q1', 10, 932],
 ['Boal', 'Paul', '2015Q2', 9, 943]]

---

** 25/30 **

You've got some extra print statements in your module that are cluttering the output you have above.

---

---

In [6]:
import jupyterimporter
from csvlist import CsvList
from pivot import pivot_columns
from joiner import join_lists

preexisting = CsvList('/midterm/preexisting.csv')
census = CsvList('/midterm/census.csv')

pre = pivot_columns([preexisting.header] + preexisting.data, list(range(2,37)))
cen = pivot_columns([census.header] + census.data, list(range(5,12)))

# DO SOME PROCESSING TO CLEANUP DATA AS NEEDED

pre_clean = [pre[0] + ['Year']] + [(r + [r[2].split(',')[1].strip()]) for r in pre[1:]]
cen_clean = [cen[0] + ['Year']] + [(r + [r[5][-4:]]) for r in cen[1:]]

out = join_lists(pre_clean, cen_clean, [0,4], [4,7], [0,2,3], [6])

[]
['4846411']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4830533']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4816089']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['4801108']
['737046']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['737442']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['731228']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['722720']
['6728783']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6630799']
['6553262']
['6553262']
['6553262']


In [7]:
out[0:10]

[['Alabama', 'Enrolled Through January 31, 2014  ', '115', '4846411'],
 ['Alabama', 'Enrolled Through December 31, 2013', '123', '4830533'],
 ['Alabama', 'Enrolled Through November 30, 2013', '594', '4830533'],
 ['Alabama', 'Enrolled Through October 31, 2013', '639', '4830533'],
 ['Alabama', 'Enrolled Through September 30, 2013', '672', '4830533'],
 ['Alabama', 'Enrolled Through August 31, 2013', '711', '4830533'],
 ['Alabama', 'Enrolled Through July 31, 2013', '736', '4830533'],
 ['Alabama', 'Enrolled Through June 30, 2013', '766', '4830533'],
 ['Alabama', 'Enrolled Through May 31, 2013', '795', '4830533'],
 ['Alabama', 'Enrolled Through April 30, 2013', '820', '4830533']]

I got the code to work with the examples and it made it through the clean, but didn't give the expected output. I've included an additional file in the upload of "midterm_working_code-kdhayes", that showes each code with the examples (even the second example for the joiner), but still didn't get it all to work here. I think the bug is likely in the joiner code, which was a patchwork of anything I could get to work and looked like it was good. The pivot seems to be working after removing the hard coding that I originally had, and making everything relative to the pivot columns. I thought that was my only problem, but it seems like the joiner is only giving a minimal output. 

For the clean up code:

The pre and cen = portions take information fromt the preexisting and census CsvLists. The .header and .data portion of csvlist class is used in both the cleanups, to split the first line of each imported list from the data, then using the pivot_columns method from the pivot class, we are pivoting data in the range of each row from items (2-37) in the preexisting data and items (5-12) from the census data. The census data is group in lists of data from each region, and starting at the second list for preexisting and the 5th list for census both start on the list including Alabama as the data of interest. 

In the pre-clean section, after the data from each of the 2 CsvLists have been identified, given a fixed header, and selected the data range that was pivoted into columns, this data is cleaned up to be joined eventually in the join_lists functions. For the preexisting condition data, the pre[0] and cen[0] are keeping the headers (I'm not sure what the 'Year' value is). 

pre_clean, preexisting Data- I think the pre[0] (and cen[0]) are to keep the header created in the pre= pivot_columns, then  skipping the header in each of the csv lists, stripping the white space around the output for the pivot columns from below the header since it is starting at pre[1:]. I'm not positive what the r[2].split(',') is doing (I think it's splitting data in cell "Enrolled Through..." then stripping the white space, then adding it back to row cleaned up). 

cen_clean, Census Data- Like the pre_clean, it adding the defined header, plus 'Year' , then the rows of data cleaned up to be used in the join_lists.

It looks like the join lists is joining by [0,4] in preexisting data, which is Alabama and probably the 'Year' which was split in the pre_clean, with the same values from the census data at [4,7]. The location of [4] I beleive is the state, Alabama in the example, and probably the 'Year' to line up the time for census data and pre-existing conditions (ie. 4830533 is repeated for all year 2013, while the only 2014 value is 4846411, which must have been filled in the pivot step). 

The output of the matching join function would be from preexisting data, the state [0], 'Enrolled...'[2] and the value for enrolled[3], which were all pivoted earlier. Then the value of census information from that corresponding year [6].

This has taken much more time than expected and my wife hates both of the name that appear on the test output lists. But please don't take that into consideration when evaluating the effort put into this coding project. 

---

** 45/50 **

Good explanation.  Your code actually is doing the right thing, but you've got a print statment in one of your modules that is cluttering up the output.  You actually have less of an issue than you think you have.

I hope that your wife will eventually forgive all of us.

---

---